### PR TITLE
Adding POST capability for topics and replies.

### PR DESCRIPTION
**Pull request by mistertwo**
Added capability to POST new replies and new topics via the API. 

New topics are POSTed to `bbp-api/v1/topics/`.
New replies to topics are POSTed to `bbp-api/v1/replies/*reply_id_here*`.

Added function in bbp-api.php for filtering whether or not output is present in fields for submission, and the API returns 422 for anything missing. Functions for information gathering on posts/topics has also been moved into their own functions within replies.php and topics.php.

Security is a concern, but nothing has been implemented for that yet.

Let me know your thoughts on these changes. :)

### CODE REVIEW

**Comment by renatonascalves** [comment]
Nice job! A few considerations:

If folks change the 'topics' and 'forums'' slugs, this change is not being reflected in the API. Should that be taken into consideration and change as well? I don't know.

More doc is needed. Also unit testing would be cool.

**Comment by mistertwo** [comment]
Thanks! I've addressed the custom slugs issue, and I've added a bit more in the way of documentation. Let me know if there's anything specific you're thinking of there, and I'll get that in place.

I'll update again once I have some good unit tests.

**Comment by renatonascalves** [comment]
Nice! 💃 

Another thing I noticed, the unit test is not depend on bbPress and it should be as you are using functions from bbPress.

I'll do so testing to suggest or outline something. Nice work! :)

**Comment by ntwb** [comment]
Loving all this, and I hope to find some time soon to take a closer look at this repo and this pull request soon, thus far I've only had the time to take a quick glance, if I've got time to spend on bbPress I'm trying to spend it on getting bbPress 2.6 shipped :)

One quick question, why rename the file `bbp-api.php` → `bbp-API.php`?

**Comment by mistertwo** [comment]
Thanks @renatonascalves ! I'll check into the dependencies for the tests and ensure that BBPress is on the list. 

Also, thanks @ntwb ! The filename was changed due to the testing framework generated by wp-cli. It appears to want the plugin directory name to match the core file for the plugin as well. Let me know if that causes any issues that you can see, and I'll get that fixed up.

**Comment by ntwb** [comment]
Thanks @mistertwo, a quick look looks like it will be fine to rename back to lowercase and then change the this line to also be lowercase https://github.com/ePascalC/bbp-API/pull/1/files#diff-10eafd8bf5fbdde867b86fe38d30b9bbR20

That said, I don't think PHPUnit will run here will it? I don't see a `phpunit.xml.dist` or `phpunit.xml` included in the PR

**Comment by ePascalC** [comment]
Great additions ! I will have a detailed look during the weekend and then merge them. Thanks for all input so far to all of you.

**Comment by mistertwo** [comment]
Cool @ePascalC ! I've pushed a couple of commits that should have the necessary files for testing. I'm still working on getting them filled out with proper tests, but let me know if you see any files missing that prevent the tests from being run on your end. Thanks!

**Comment by renatonascalves** [comment]
@mistertwo I'm testing right now and none of phpunit tests is passing... Also I'll be sending some commits with a few updates.

**Comment by mistertwo** [comment]
Ooh that's not good. I'll be keeping an eye here.

@renatonascalves let me know of the specific errors that you're seeing on your end. I've initialized my testing environment via WP-CLI, running within VVV. Let me know some of the specific errors you're seeing, and I'll help you track those down.

**Comment by mistertwo** [comment]
Hey @renatonascalves, I've just spun up a fresh copy of VVV, and cloned the repo over. The tests are still coming up clean on this end. Let me know if running the tests within VVV results in the same for you.

**Comment by ePascalC** [comment]
First checks seem great. Will do some more and then see to upgrade the plugin on the w.org repository! Thanks a lot

**Comment by renatonascalves** [comment]
My tests passed! The problem was with my vvv setup. 

Glad it was merged! A few suggestions of improvements, some I'll be sending as PR in the coming days:

- Composer support
- Clean the code
- Follow WordPress Standards

**Pull request merged**
